### ISSUE TITLE
COMError... i think it is a permission issue?

### ISSUE THREAD

**Issue by jason79** [DeepHorizons/tts#2]
import tts.sapi

directory= 'D:\\Google Drive\\python\\'
voice = tts.sapi.Sapi()
voice.set_voice("IVONA 2 Joey")
voice.create_recording(directory+'hello.wav', "Hello")

I can write to this directory with other python scripts, but not sure why I can't do it here. 

Traceback (most recent call last):
  File "D:\Google drive\python\test3.py", line 6, in <module>
    voice.create_recording(directory+'hello.wav', "Hello")
  File "C:\Python27\lib\site-packages\tts\sapi.py", line 104, in create_recording
    stream = self._create_stream(filename)
  File "C:\Python27\lib\site-packages\tts\sapi.py", line 97, in _create_stream
    stream.Open(filename, SpeechLib.SSFMCreateForWrite)
COMError: (-2147287038, None, (None, None, None, 0, None))

**Comment by DeepHorizons** [comment]
I think its because you are using backslashes. Your directory string should look like `directory= 'D:/Google Drive/python/'`. This is because Python uses backslashes in strings to specify special characters (like \n, \r, ect.) Forward slashes work just fine on windows.
